export const titulos = [
  'Demasiados árboles',
  'Odio de clase',
  'Buenavista',
  'Vivo en el limbo',
  'Utopía',
  'Un ladrón',
  'Obrero raso',
  'Desposeído',
  'Chambonada #1',
  'Chambonada #2',
  'Chambonada #3',
  'Polvos',
  'Sexy',
  'Sexy II',
  'Canto I',
  'Canto II',
  'Canto III',
  'Canto IV',
  'Canto V',
  'Melodrama',
  'La luz',
  'La ética de Peñómaco',
  'Pornografía de los lepidópteros',
  '¿Los pobres? A metros',
];

export const frases = [
  'licuadoras luminosas',
  'el que roba es un ladrón',
  'estoy seguro de que muy pronto vamos a tener venados',
  'no poseo ni una rueda de Transmilenio',
  'en ocho años se podrá nadar en el río Bogotá',
  'trenes ligeros son juguetes muy costosos',
  'la poca inteligencia que yo tengo es muy poca',
  'también hemos sembrado miles de buganvilias',
  'el criterio de diseño de los parques del norte es que ningún obrero pueda jugar fútbol al almuerzo',
  'los llenan de árboles y nadie va',
  'yo me acuerdo como a los 2 o 3 días en la ducha',
  'trabajé como obrero raso',
  'en una construcción',
  'tan raso que era el único no negro de la obra',
  'un ladrón no es alguien que nació ladrón',
  'artista con objetivos grandiosos',
  'no',
  'nadie nace ladrón, ladrón es el que roba',
  'entonces',
  'la persona que roba no es una persona buena que roba de vez en cuando',
  'no es de izquierda dejar que los postes de la ciudad se llenen de afiches y los puentes de mamarrachos',
  'es mugre, es chambonada',
  'el problema de la contaminación es el polvo',
  'no los motores de los buses',
  'a la gente le parece muy sexy',
  'no es sexy hablar de cárceles',
  'en campaña presidencial',
  'realmente no nos "perdimos" en los bosques orientales de Bogotá',
  'sabíamos para dónde íbamos',
  'pero no había senderos',
  'y la vegetación era totalmente tupida',
  'había barrancos y riscos',
  'disfrutamos',
  'la naturaleza',
  'y la camaradería',
  'ya anocheciendo',
  'los que ahora deciden y opinan',
  'vieron las tumbas',
  'cuando exhumé los cuerpos',
  'el muro por reja',
  'pero para la élite',
  'de seres superiores',
  'impactar en la memoria nacional',
  'las auras de los muertos',
  'hicimos acera amplia',
  'con lo que cuesta el predio-pedestal',
  'había un cementerio encerrado por un muro',
  'debo confesar que es bueno para el ambiente emocional',
  'los parques también necesitan espacios donde entre la luz',
  'bancas, juegos infantiles, etcétera',
  'escenario de un melodrama',
  'clasista',
  'difrazado de tragedia',
  'condimentado',
  'con politiquería',
  'pagar el pasaje es lo correcto',
  'colarse es lo corrupto',
  'imagínese caminar por el sendero de las mariposas',
  '(con su pareja)',
  'y verlas apareándose',
  'los ricos del país que viven en la capital',
  'quieren tener el metro (subterráneo)',
  'para que los pobres que se movilicen en él no se vean',
  'a algunos las emociones de las ilusiones políticas les nublan la objetividad',
];
